#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

cd "$(dirname "$0")"

STAMP="$(date +%Y%m%d-%H%M%S)"

echo "========================================"
echo " EXAM DARPAN GROWTH + PUBLISH SAFETY PATCH"
echo "========================================"
echo

echo "[1/8] Checking clean Python syntax..."
python3 -m py_compile scripts/generate_static.py

echo "[2/8] Creating backups..."
cp scripts/generate_static.py "scripts/generate_static.py.before-growth-patch-${STAMP}"
cp .github/workflows/static-seo-deploy.yml ".github/workflows/static-seo-deploy.yml.before-growth-patch-${STAMP}"

echo "[3/8] Patching static generator..."

python3 - <<'PY'
from pathlib import Path

p = Path("scripts/generate_static.py")
s = p.read_text(encoding="utf-8")

changes = 0

# ------------------------------------------------------------
# SAFETY 1: Never deploy an empty Firestore result.
# ------------------------------------------------------------
old = '''    try:
        posts = fetch_posts()
    except Exception as exc:
        print(f"ERROR: Firestore static build failed: {exc}", file=sys.stderr)
        return 2

    # Remove only files previously generated by this builder; hand-authored pages stay untouched.
'''
new = '''    try:
        posts = fetch_posts()
    except Exception as exc:
        print(f"ERROR: Firestore static build failed: {exc}", file=sys.stderr)
        return 2

    # SAFETY: an empty Firestore response is never treated as a valid build.
    # Otherwise cleanup_generated_files() could delete all generated article pages
    # and Firebase Hosting could deploy an empty article set.
    if not posts:
        print(
            "ERROR: Firestore returned ZERO published posts. "
            "Refusing to clean or deploy generated article pages.",
            file=sys.stderr,
        )
        return 3

    # SAFETY: duplicate slugs must never be silently dropped.
    slug_to_ids: dict[str, list[str]] = {}
    for p in posts:
        slug = slugify(p.get("slug"))
        if slug:
            slug_to_ids.setdefault(slug, []).append(str(p.get("id", "")))

    duplicate_slugs = {
        slug: ids for slug, ids in slug_to_ids.items()
        if len(ids) > 1
    }
    if duplicate_slugs:
        print("ERROR: Duplicate published article slugs detected:", file=sys.stderr)
        for slug, ids in sorted(duplicate_slugs.items()):
            print(f"  {slug}: {', '.join(ids)}", file=sys.stderr)
        print(
            "Refusing build so one published article cannot silently disappear.",
            file=sys.stderr,
        )
        return 4

    # Remove only files previously generated by this builder; hand-authored pages stay untouched.
'''
if old not in s:
    raise SystemExit("PATCH FAILED: main() safety anchor not found")
s = s.replace(old, new, 1)
changes += 1

# ------------------------------------------------------------
# SAFETY 2: Never silently skip duplicate slug in generation loop.
# ------------------------------------------------------------
old = '''    article_slugs: list[str] = []
    seen: set[str] = set()
    for p in posts:
        s = slugify(p.get("slug"))
        if not s or s in seen or s in RESERVED_SLUGS:
            continue
        (PUBLIC / f"{s}.html").write_text(article_page(p, posts), encoding="utf-8")
        article_slugs.append(s)
        seen.add(s)
'''
new = '''    article_slugs: list[str] = []
    seen: set[str] = set()
    for p in posts:
        s = slugify(p.get("slug"))

        if not s:
            print(
                f"WARNING: Published post {p.get('id', '')} has no usable slug; "
                "skipping that post.",
                file=sys.stderr,
            )
            continue

        if s in RESERVED_SLUGS:
            raise RuntimeError(
                f"Published post {p.get('id', '')} uses reserved slug '{s}'. "
                "Refusing build so the article cannot silently disappear."
            )

        if s in seen:
            raise RuntimeError(
                f"Duplicate generated slug '{s}'. Refusing build."
            )

        (PUBLIC / f"{s}.html").write_text(
            article_page(p, posts),
            encoding="utf-8",
        )
        article_slugs.append(s)
        seen.add(s)
'''
if old not in s:
    raise SystemExit("PATCH FAILED: article generation loop anchor not found")
s = s.replace(old, new, 1)
changes += 1

# ------------------------------------------------------------
# GROWTH 1: More homepage crawlable article links.
# 24 -> 36.
# ------------------------------------------------------------
old = 'for i, p in enumerate(posts[:24]):'
new = 'for i, p in enumerate(posts[:36]):'
if old not in s:
    raise SystemExit("PATCH FAILED: homepage 24-post anchor not found")
s = s.replace(old, new, 1)
changes += 1

# ------------------------------------------------------------
# GROWTH 2: More related internal links on every article.
# 6 -> 8.
# ------------------------------------------------------------
old = 'related = related_posts(p, posts)'
new = 'related = related_posts(p, posts, limit=8)'
if old not in s:
    raise SystemExit("PATCH FAILED: related-post anchor not found")
s = s.replace(old, new, 1)
changes += 1

# ------------------------------------------------------------
# GROWTH 3: Make the article's related section more explicit
# for users + crawlers without stuffing keywords.
# ------------------------------------------------------------
old = '<span class="eyebrow">YOU MAY ALSO LIKE</span><h2>Related Updates</h2>'
new = '<span class="eyebrow">MORE FROM EXAM DARPAN</span><h2>Related Updates</h2>'
if old not in s:
    raise SystemExit("PATCH FAILED: related heading anchor not found")
s = s.replace(old, new, 1)
changes += 1

# ------------------------------------------------------------
# GROWTH 4: Add a compact crawlable "latest updates" block
# to every article, immediately before the community CTA.
#
# This gives an article another route to newer pages.
# It is generated from the same published-post dataset.
# ------------------------------------------------------------
anchor = '''    related_html = ""
    if related:
'''
if anchor not in s:
    raise SystemExit("PATCH FAILED: related_html anchor not found")

# We only add helper once.
helper_marker = 'def article_latest_links('
if helper_marker not in s:
    insert_before = 'def article_page(p: dict[str, Any], posts: list[dict[str, Any]]) -> str:\\n'
    helper = r'''def article_latest_links(
    post: dict[str, Any],
    posts: list[dict[str, Any]],
    limit: int = 5,
) -> str:
    """Small crawlable list of recent published articles for article-to-article discovery."""
    current_id = post.get("id")
    current_slug = slugify(post.get("slug"))

    items: list[str] = []
    for other in posts:
        if other.get("id") == current_id:
            continue

        other_slug = slugify(other.get("slug"))
        if not other_slug or other_slug == current_slug:
            continue

        items.append(
            f'<li><a href="{esc(article_path(other_slug))}">'
            f'{esc(post_title(other))}</a></li>'
        )

        if len(items) >= limit:
            break

    if not items:
        return ""

    return (
        '<section class="article-latest-links card pad">'
        '<div class="section-title">'
        '<div><span class="eyebrow">LATEST UPDATES</span>'
        '<h2>नई Updates</h2></div>'
        '</div>'
        '<ul class="article-latest-list">'
        + "".join(items)
        + '</ul>'
        '</section>'
    )


'''
    if insert_before not in s:
        raise SystemExit("PATCH FAILED: article_page definition anchor not found")
    s = s.replace(insert_before, helper + insert_before, 1)
    changes += 1

# Add latest_html variable.
old = '''    related = related_posts(p, posts, limit=8)
    content = clean_article_content(p.get("content")) or "<p>इस article का content अभी उपलब्ध नहीं है।</p>"
'''
new = '''    related = related_posts(p, posts, limit=8)
    latest_links_html = article_latest_links(p, posts, limit=5)
    content = clean_article_content(p.get("content")) or "<p>इस article का content अभी उपलब्ध नहीं है।</p>"
'''
if old not in s:
    raise SystemExit("PATCH FAILED: article variable anchor not found")
s = s.replace(old, new, 1)
changes += 1

# Insert before final community card.
old = '''{related_html}
<section class="community-card">
'''
new = '''{related_html}
{latest_links_html}
<section class="community-card">
'''
if old not in s:
    raise SystemExit("PATCH FAILED: article latest-links insertion anchor not found")
s = s.replace(old, new, 1)
changes += 1

p.write_text(s, encoding="utf-8")

print(f"Generator patch applied: {changes} changes")
PY

echo "[4/8] Patching workflow verification..."

python3 - <<'PY'
from pathlib import Path

p = Path(".github/workflows/static-seo-deploy.yml")
s = p.read_text(encoding="utf-8")

changes = 0

# Better build logging + hard verification.
old = '''      - name: Verify generated SEO files
        run: |
          test -f public/sitemap.xml
          test -f public/robots.txt || true
          echo "Generated article pages:"
          find public -maxdepth 1 -type f -name "*.html" | wc -l
'''
new = '''      - name: Verify generated SEO files
        run: |
          set -euo pipefail

          test -f public/sitemap.xml

          ARTICLE_COUNT="$(grep -rl --include="*.html" "EXAM-DARPAN-GENERATED-ARTICLE" public | wc -l | tr -d ' ')"
          SITEMAP_COUNT="$(grep -c "<loc>" public/sitemap.xml || true)"

          echo "Generated article pages: ${ARTICLE_COUNT}"
          echo "Sitemap URLs: ${SITEMAP_COUNT}"

          # A successful Firebase read must produce at least one article.
          test "${ARTICLE_COUNT}" -gt 0

          # Keep a machine-readable build summary in the Actions log.
          echo "BUILD_ARTICLE_COUNT=${ARTICLE_COUNT}"
          echo "BUILD_SITEMAP_COUNT=${SITEMAP_COUNT}"
'''
if old not in s:
    raise SystemExit("PATCH FAILED: workflow verification anchor not found")
s = s.replace(old, new, 1)
changes += 1

# Make the deploy output easier to diagnose.
old = '''      - name: Deploy Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          printf '%s' "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > /tmp/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json
          firebase use examdarpan-dd963
          firebase deploy --only hosting --non-interactive
'''
new = '''      - name: Deploy Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          set -euo pipefail

          printf '%s' "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > /tmp/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/firebase-service-account.json

          firebase use examdarpan-dd963

          echo "Deploying generated Exam Darpan SEO build..."
          firebase deploy --only hosting --non-interactive
'''
if old not in s:
    raise SystemExit("PATCH FAILED: workflow deploy anchor not found")
s = s.replace(old, new, 1)
changes += 1

p.write_text(s, encoding="utf-8")

print(f"Workflow patch applied: {changes} changes")
PY

echo "[5/8] Syntax + shell/YAML sanity..."

python3 -m py_compile scripts/generate_static.py

python3 - <<'PY'
from pathlib import Path

g = Path("scripts/generate_static.py").read_text(encoding="utf-8")
w = Path(".github/workflows/static-seo-deploy.yml").read_text(encoding="utf-8")

checks = [
    ("zero-post safety", "if not posts:" in g),
    ("duplicate-slug safety", "Duplicate published article slugs detected" in g),
    ("homepage 36", "posts[:36]" in g),
    ("8 related articles", "related_posts(p, posts, limit=8)" in g),
    ("latest article links", "def article_latest_links(" in g),
    ("workflow article verification", 'ARTICLE_COUNT="$(grep -rl' in w),
]

failed = [name for name, ok in checks if not ok]
if failed:
    raise SystemExit("VERIFY FAILED: " + ", ".join(failed))

print("ALL PATCH CHECKS PASSED")
PY

echo "[6/8] Showing exact changed areas..."
git diff -- scripts/generate_static.py .github/workflows/static-seo-deploy.yml | sed -n '1,260p'

echo
echo "[7/8] Local Git status..."
git status --short

echo
echo "[8/8] DONE"
echo
echo "Backups created with timestamp:"
echo "  scripts/generate_static.py.before-growth-patch-${STAMP}"
echo "  .github/workflows/static-seo-deploy.yml.before-growth-patch-${STAMP}"
echo
echo "IMPORTANT:"
echo "This patch has NOT pushed anything to GitHub."
echo "Review the diff above."
echo
echo "If diff looks correct, run:"
echo "  git add scripts/generate_static.py .github/workflows/static-seo-deploy.yml"
echo "  git commit -m \"Strengthen article discovery and publish safety\""
echo "  git push origin main"
