#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

cd "$(dirname "$0")"

STAMP="$(date +%Y%m%d-%H%M%S)"

echo "=============================================="
echo " EXAM DARPAN GROWTH + PUBLISH SAFETY V3"
echo "=============================================="

echo "[1/8] Pre-flight..."
python3 -m py_compile scripts/generate_static.py

echo "[2/8] Backups..."
cp scripts/generate_static.py \
  "scripts/generate_static.py.before-growth-v3-${STAMP}"

cp .github/workflows/static-seo-deploy.yml \
  ".github/workflows/static-seo-deploy.yml.before-growth-v3-${STAMP}"

echo "[3/8] Patching generator..."

python3 - <<'PY'
from pathlib import Path

p = Path("scripts/generate_static.py")
s = p.read_text(encoding="utf-8")

changes = []

# ------------------------------------------------------------
# 1. ZERO-POST SAFETY
# Insert immediately after successful fetch_posts().
# ------------------------------------------------------------

anchor = '''    except Exception as exc:
        print(f"ERROR: Firestore static build failed: {exc}", file=sys.stderr)
        return 2

    # Remove only files previously generated by this builder; hand-authored pages stay untouched.
'''

replacement = '''    except Exception as exc:
        print(f"ERROR: Firestore static build failed: {exc}", file=sys.stderr)
        return 2

    # SAFETY: Never treat an empty Firestore result as a valid build.
    # If Firestore unexpectedly returns zero published posts, cleanup must not
    # delete the currently generated article pages.
    if not posts:
        print(
            "ERROR: Firestore returned ZERO published posts. "
            "Refusing to clean or deploy generated article pages.",
            file=sys.stderr,
        )
        return 3

    # Remove only files previously generated by this builder; hand-authored pages stay untouched.
'''

if anchor not in s:
    raise SystemExit("FAILED: zero-post anchor not found")

s = s.replace(anchor, replacement, 1)
changes.append("zero-post safety")

# ------------------------------------------------------------
# 2. DUPLICATE SLUG SAFETY
# Insert before cleanup_generated_files().
# ------------------------------------------------------------

anchor = '''    # Remove only files previously generated by this builder; hand-authored pages stay untouched.
    cleanup_generated_files()
'''

replacement = '''    # Published articles must have unique, usable slugs.
    # Otherwise one article can silently disappear from the generated site.
    slug_to_ids: dict[str, list[str]] = {}

    for post in posts:
        slug = slugify(post.get("slug"))

        if not slug:
            print(
                f"ERROR: Published post {post.get('id', '')} has no usable slug.",
                file=sys.stderr,
            )
            return 4

        if slug in RESERVED_SLUGS:
            print(
                f"ERROR: Published post {post.get('id', '')} uses reserved slug '{slug}'.",
                file=sys.stderr,
            )
            return 4

        slug_to_ids.setdefault(slug, []).append(str(post.get("id", "")))

    duplicate_slugs = {
        slug: ids
        for slug, ids in slug_to_ids.items()
        if len(ids) > 1
    }

    if duplicate_slugs:
        print("ERROR: Duplicate published article slugs detected:", file=sys.stderr)
        for slug, ids in sorted(duplicate_slugs.items()):
            print(f"  {slug}: {', '.join(ids)}", file=sys.stderr)

        print(
            "Refusing build so a published article cannot silently disappear.",
            file=sys.stderr,
        )
        return 5

    # Remove only files previously generated by this builder; hand-authored pages stay untouched.
    cleanup_generated_files()
'''

if anchor not in s:
    raise SystemExit("FAILED: duplicate-slug/cleanup anchor not found")

s = s.replace(anchor, replacement, 1)
changes.append("duplicate-slug safety")

# ------------------------------------------------------------
# 3. HOMEPAGE DISCOVERY: 24 -> 36
# ------------------------------------------------------------

if "posts[:24]" not in s:
    raise SystemExit("FAILED: homepage 24-post limit not found")

s = s.replace("posts[:24]", "posts[:36]", 1)
changes.append("homepage discovery 24->36")

# ------------------------------------------------------------
# 4. RELATED ARTICLES: default 6 -> 8
# ------------------------------------------------------------

old = "def related_posts(post: dict[str, Any], posts: list[dict[str, Any]], limit: int = 6)"
new = "def related_posts(post: dict[str, Any], posts: list[dict[str, Any]], limit: int = 8)"

if old not in s:
    raise SystemExit("FAILED: related_posts limit definition not found")

s = s.replace(old, new, 1)

# Explicitly use 8 in article generation as well.
old = "    related = related_posts(p, posts)"
new = "    related = related_posts(p, posts, limit=8)"

if old not in s:
    raise SystemExit("FAILED: article related_posts call not found")

s = s.replace(old, new, 1)
changes.append("related discovery 6->8")

# ------------------------------------------------------------
# 5. GENERATION LOOP: do not silently skip invalid slugs
# ------------------------------------------------------------

old = '''    for p in posts:
        s = slugify(p.get("slug"))
        if not s or s in seen or s in RESERVED_SLUGS:
            continue
        (PUBLIC / f"{s}.html").write_text(article_page(p, posts), encoding="utf-8")
        article_slugs.append(s)
        seen.add(s)
'''

new = '''    for p in posts:
        s = slugify(p.get("slug"))

        if not s:
            raise RuntimeError(
                f"Published post {p.get('id', '')} has no usable slug."
            )

        if s in RESERVED_SLUGS:
            raise RuntimeError(
                f"Published post {p.get('id', '')} uses reserved slug '{s}'."
            )

        if s in seen:
            raise RuntimeError(
                f"Duplicate generated article slug '{s}'."
            )

        (PUBLIC / f"{s}.html").write_text(
            article_page(p, posts),
            encoding="utf-8",
        )

        article_slugs.append(s)
        seen.add(s)
'''

if old not in s:
    raise SystemExit("FAILED: main article generation loop not found")

s = s.replace(old, new, 1)
changes.append("strict article generation loop")

p.write_text(s, encoding="utf-8")

print("Generator patch applied:")
for item in changes:
    print("  OK:", item)
PY

echo "[4/8] Patching GitHub Actions verification..."

python3 - <<'PY'
from pathlib import Path

p = Path(".github/workflows/static-seo-deploy.yml")
s = p.read_text(encoding="utf-8")

old = '''      - name: Verify generated SEO files
        run: |
          test -f public/sitemap.xml
          test -f public/robots.txt || true
          echo "Generated article pages:"
          find public -maxdepth 1 -type f -name "*.html" | wc -l
'''

new = '''      - name: Verify generated SEO files
        run: |
          set -euo pipefail

          test -f public/sitemap.xml

          ARTICLE_COUNT="$(grep -rl --include="*.html" "EXAM-DARPAN-GENERATED-ARTICLE" public | wc -l | tr -d ' ')"
          SITEMAP_COUNT="$(grep -c "<loc>" public/sitemap.xml || true)"

          echo "Generated article pages: ${ARTICLE_COUNT}"
          echo "Sitemap URLs: ${SITEMAP_COUNT}"

          # A successful Firestore build must contain at least one article.
          test "${ARTICLE_COUNT}" -gt 0

          # Every generated article must have a sitemap entry.
          test "${SITEMAP_COUNT}" -ge "${ARTICLE_COUNT}"
'''

if old not in s:
    raise SystemExit("FAILED: workflow verification block not found")

s = s.replace(old, new, 1)

p.write_text(s, encoding="utf-8")

print("Workflow verification patched.")
PY

echo "[5/8] Syntax verification..."
python3 -m py_compile scripts/generate_static.py

echo "[6/8] Patch verification..."

python3 - <<'PY'
from pathlib import Path

g = Path("scripts/generate_static.py").read_text(encoding="utf-8")
w = Path(".github/workflows/static-seo-deploy.yml").read_text(encoding="utf-8")

checks = {
    "zero-post safety": 'if not posts:' in g,
    "duplicate slug safety": 'Duplicate published article slugs detected' in g,
    "homepage 36": 'posts[:36]' in g,
    "related default 8": 'limit: int = 8' in g,
    "related call 8": 'related_posts(p, posts, limit=8)' in g,
    "strict generation": 'Duplicate generated article slug' in g,
    "workflow article count": 'ARTICLE_COUNT=' in w,
    "workflow sitemap count": 'SITEMAP_COUNT=' in w,
}

failed = [name for name, ok in checks.items() if not ok]

if failed:
    raise SystemExit("VERIFY FAILED: " + ", ".join(failed))

print("ALL PATCH CHECKS PASSED")
PY

echo "[7/8] Diff..."

git diff -- scripts/generate_static.py .github/workflows/static-seo-deploy.yml

echo
echo "[8/8] Final status..."

git status --short

echo
echo "=============================================="
echo " PATCH SUCCESSFUL"
echo "=============================================="
echo
echo "IMPORTANT:"
echo "Nothing has been committed or pushed."
echo
echo "If the diff is correct, run:"
echo
echo 'git add scripts/generate_static.py .github/workflows/static-seo-deploy.yml'
echo 'git commit -m "Strengthen article discovery and publish safety"'
echo 'git push origin main'
echo
echo "Backup files:"
echo "scripts/generate_static.py.before-growth-v3-${STAMP}"
echo ".github/workflows/static-seo-deploy.yml.before-growth-v3-${STAMP}"
