#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail

cd "$(dirname "$0")"
STAMP="$(date +%Y%m%d-%H%M%S)"

echo "=============================================="
echo " EXAM DARPAN FINAL GROWTH + PUBLISH SAFETY V2"
echo "=============================================="

echo
echo "[1/9] Pre-flight syntax..."
python3 -m py_compile scripts/generate_static.py

echo
echo "[2/9] Backups..."
cp scripts/generate_static.py \
  "scripts/generate_static.py.before-growth-v2-${STAMP}"

cp .github/workflows/static-seo-deploy.yml \
  ".github/workflows/static-seo-deploy.yml.before-growth-v2-${STAMP}"

echo
echo "[3/9] Patching generator..."

python3 - <<'PY'
from pathlib import Path

p = Path("scripts/generate_static.py")
s = p.read_text(encoding="utf-8")

changes = []

# ---------------------------------------------------------
# 1. ZERO PUBLISHED POSTS = BUILD FAILURE
# ---------------------------------------------------------
old = """    try:
        posts = fetch_posts()
    except Exception as exc:                             print(f"ERROR: Firestore static build failed: {exc}", file=sys.stderr)
        return 2                                 
    # Remove only files previously generated by this builder; hand-authored pages stay untouched.     cleanup_generated_files()
"""

new = """    try:
        posts = fetch_posts()
    except Exception as exc:
        print(
            f"ERROR: Firestore static build failed: {exc}",
            file=sys.stderr,
        )
        return 2

    # Never treat an empty Firestore result as a valid production build.
    # This prevents cleanup + deploy from removing previously generated
    # article pages when Firebase credentials/query/config temporarily fail.
    if not posts:
        print(
            "ERROR: Firestore returned ZERO published posts. "
            "Refusing production build.",
            file=sys.stderr,
        )
        return 3

    # Remove only files previously generated by this builder;
    # hand-authored pages stay untouched.
    cleanup_generated_files()
"""

if old not in s:
    raise SystemExit("FAILED: main Firestore/cleanup anchor not found")

s = s.replace(old, new, 1)
changes.append("zero-post production safety")

# ---------------------------------------------------------
# 2. DUPLICATE SLUG SAFETY
# ---------------------------------------------------------
old = """    article_slugs: list[str] = []                    seen: set[str] = set()
    for p in posts:
        s = slugify(p.get("slug"))
        if not s or s in seen or s in RESERVED_SLUGS:
            continue                                     (PUBLIC / f"{s}.html").write_text(article_page(p, posts), encoding="utf-8")
        article_slugs.append(s)
        seen.add(s)                                                                                   (PUBLIC / "exam-calendar.html").write_text(exam_calendar_page(posts), encoding="utf-8")
"""

new = """    # Validate published article slugs before generating files.
    slug_owner: dict[str, str] = {}

    for p in posts:
        s = slugify(p.get("slug"))
        post_id = str(p.get("id", ""))

        if not s:
            raise RuntimeError(
                f"Published post {post_id} has no usable slug."
            )

        if s in RESERVED_SLUGS:
            raise RuntimeError(
                f"Published post {post_id} uses reserved slug '{s}'."
            )

        if s in slug_owner:
            raise RuntimeError(
                f"Duplicate published slug '{s}' detected. "
                f"Posts: {slug_owner[s]} and {post_id}"
            )

        slug_owner[s] = post_id

    article_slugs: list[str] = []
    seen: set[str] = set()

    for p in posts:
        s = slugify(p.get("slug"))

        if not s:
            continue

        if s in seen:
            raise RuntimeError(
                f"Duplicate generated slug '{s}'."
            )

        (PUBLIC / f"{s}.html").write_text(
            article_page(p, posts),
            encoding="utf-8",
        )

        article_slugs.append(s)
        seen.add(s)

    (PUBLIC / "exam-calendar.html").write_text(
        exam_calendar_page(posts),
        encoding="utf-8",
    )
"""

if old not in s:
    raise SystemExit("FAILED: main article generation block not found")

s = s.replace(old, new, 1)
changes.append("duplicate/reserved slug safety")

# ---------------------------------------------------------
# 3. HOMEPAGE DISCOVERY 24 -> 36
# ---------------------------------------------------------
old = "for i, p in enumerate(posts[:24]):"
new = "for i, p in enumerate(posts[:36]):"

if old not in s:
    raise SystemExit("FAILED: homepage 24-post anchor not found")

s = s.replace(old, new, 1)
changes.append("homepage discovery 24 -> 36")

# ---------------------------------------------------------
# 4. RELATED ARTICLES 6 -> 8
# ---------------------------------------------------------
old = "related = related_posts(p, posts)"
new = "related = related_posts(p, posts, limit=8)"

if old not in s:
    raise SystemExit("FAILED: related article anchor not found")

s = s.replace(old, new, 1)
changes.append("related articles 6 -> 8")

p.write_text(s, encoding="utf-8")

print("Generator changes:")
for item in changes:
    print("  OK:", item)
PY

echo
echo "[4/9] Patching workflow verification..."

python3 - <<'PY'
from pathlib import Path

p = Path(".github/workflows/static-seo-deploy.yml")
s = p.read_text(encoding="utf-8")

old = """      - name: Verify generated SEO files
        run: |
          test -f public/sitemap.xml
          test -f public/robots.txt || true
          echo "Generated article pages:"
          find public -maxdepth 1 -type f -name "*.html" | wc -l
"""

new = """      - name: Verify generated SEO files
        run: |
          set -euo pipefail

          test -f public/sitemap.xml

          ARTICLE_COUNT="$(grep -rl --include='*.html' 'EXAM-DARPAN-GENERATED-ARTICLE' public | wc -l | tr -d ' ')"
          SITEMAP_COUNT="$(grep -c '<loc>' public/sitemap.xml || true)"

          echo "Generated article pages: ${ARTICLE_COUNT}"
          echo "Sitemap URLs: ${SITEMAP_COUNT}"

          # Firebase must return at least one published article.
          test "${ARTICLE_COUNT}" -gt 0

          # Sitemap must contain at least the generated article set.
          test "${SITEMAP_COUNT}" -ge "${ARTICLE_COUNT}"
"""

if old not in s:
    raise SystemExit("FAILED: workflow verification block not found")

s = s.replace(old, new, 1)

p.write_text(s, encoding="utf-8")

print("Workflow verification patched.")
PY

echo
echo "[5/9] Syntax verification..."
python3 -m py_compile scripts/generate_static.py

echo
echo "[6/9] Structural verification..."

python3 - <<'PY'
from pathlib import Path

g = Path("scripts/generate_static.py").read_text(encoding="utf-8")
w = Path(".github/workflows/static-seo-deploy.yml").read_text(encoding="utf-8")

checks = [
    ("zero-post safety", 'if not posts:' in g),
    ("duplicate slug safety", "Duplicate published slug" in g),
    ("reserved slug safety", "uses reserved slug" in g),
    ("homepage 36", "posts[:36]" in g),
    ("related limit 8", "related_posts(p, posts, limit=8)" in g),
    ("workflow article count", "ARTICLE_COUNT=" in w),
    ("workflow non-empty build", 'test "${ARTICLE_COUNT}" -gt 0' in w),
]

failed = [name for name, ok in checks if not ok]

if failed:
    raise SystemExit(
        "VERIFY FAILED:\n" +
        "\n".join(" - " + x for x in failed)
    )

print("ALL STRUCTURAL CHECKS PASSED")
PY

echo
echo "[7/9] Showing important diff..."
git diff -- scripts/generate_static.py .github/workflows/static-seo-deploy.yml

echo
echo "[8/9] Current article/sitemap state..."
echo "Local article HTML:"
git ls-files 'public/*.html' | grep -vE \
'/(index|article|about|contact|privacy|terms|disclaimer|editorial-policy|404|quiz|firebase-init|author)\.html$' \
| wc -l

echo "Local sitemap URLs:"
grep -c '<loc>' public/sitemap.xml || true

echo
echo "[9/9] DONE"
echo
echo "IMPORTANT:"
echo "Nothing has been committed or pushed."
echo
echo "Backups:"
echo "scripts/generate_static.py.before-growth-v2-${STAMP}"
echo ".github/workflows/static-seo-deploy.yml.before-growth-v2-${STAMP}"
echo
echo "If the diff is correct:"
echo "git add scripts/generate_static.py .github/workflows/static-seo-deploy.yml"
echo 'git commit -m "Strengthen article publishing safety and discovery"'
echo "git push origin main"
